/** Allowed product analytics events (whitelist for /api/product-events). */
export const ALLOWED_PRODUCT_EVENTS = new Set([
  "page_view",
  "job_viewed",
  "apply_clicked",
  "apply_requires_auth",
  "apply_resumed_after_auth",
  "application_dialog_opened",
  "application_dialog_cancelled",
  "application_started",
  "application_submitted",
  "search_performed",
  "filter_applied",
  "back_to_list_clicked",
  "job_shared",
  "hospital_shared",
  "maps_opened",
  "nearby_page_viewed",
  "location_permission_granted",
  "nearby_shift_clicked",
  "hospital_viewed",
  "hospital_profile_viewed",
  "hospital_review_read",
  "hospital_view_shifts_clicked",
  "hospital_followed",
  "hospital_apply_started",
  "hospital_jobs_viewed",
  "auth_started",
  "auth_completed",
  "auth_abandoned",
  "auth_started_from_job",
  "auth_completed_from_job",
  "profile_started",
  "profile_completed",
  "hospital_signup_started",
  "hospital_signup_completed",
  "job_created",
  "job_published",
  "professional_accepted",
  "professional_rejected",
  "error_boundary_triggered",
  "verification_started",
  "verification_document_uploaded",
  "verification_submitted",
  "verification_approved",
  "verification_rejected",
]);

export const FUNNEL_EVENTS = [
  "job_viewed",
  "apply_clicked",
  "apply_requires_auth",
  "apply_resumed_after_auth",
  "nearby_page_viewed",
  "location_permission_granted",
  "nearby_shift_clicked",
  "auth_started",
  "auth_completed",
  "auth_abandoned",
  "auth_started_from_job",
  "auth_completed_from_job",
  "profile_started",
  "profile_completed",
  "application_started",
  "application_submitted",
] as const;

export const SUPABASE_PROJECT_REF = "qxrrjpepoyubksiuxany";

export const QUICK_LINKS = {
  vercelAnalytics: "https://vercel.com/dashboard",
  vercelSpeedInsights: "https://vercel.com/dashboard",
  sentry: "https://sentry.io/organizations/medibrick/projects/medibrick-frontend/",
  supabaseLogs: `https://supabase.com/dashboard/project/${SUPABASE_PROJECT_REF}/logs/explorer`,
  supabaseSql: `https://supabase.com/dashboard/project/${SUPABASE_PROJECT_REF}/sql/new`,
} as const;
